version: '3.8'

services:
  db:
    image: postgres:16
    container_name: funds_postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: funds_db
    ports:
      - "5432:5432"
    volumes:
      - funds_db_data:/var/lib/postgresql/data

  scraper:
    build: .
    container_name: fund_etl_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./validation_output:/app/validation_output

    tty: true 

volumes:
  funds_db_data:
