version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fund_db_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-fund_data}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: .
    container_name: fund_etl_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./validation_output:/app/validation_output

    tty: true 

volumes:
  postgres_data: