version: '3.8'

services:
  db:
    image: postgres:16
    container_name: funds_postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: funds_db
    ports:
      - "5433:5432"
    volumes:
      - funds_db_data:/var/lib/postgresql/data

  scraper:
    build: .
    container_name: fund_etl_app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./validation_output:/app/validation_output

    tty: true 

  pgadmin:
    image: dpage/pgadmin4
    container_name: funds_pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: atom@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
 
volumes:
  funds_db_data:
  pgadmin_data:
